### ISSUE TITLE
Tracking Issue: Full Fast Sync Support

### ISSUE THREAD

**Issue by liuchengxu** [subcoin-project/subcoin#56]
The fast sync feature in Subcoin has been demonstrated to work, but it is not yet fully functional for practical use. Specifically, syncing to the latest Bitcoin state via fast sync is currently infeasible due to certain limitations within the Substrate framework. This issue tracks the progress toward a fully operational fast sync feature that is user-friendly and capable of syncing to the tip of the Bitcoin network.

#### Key Obstacles

- [ ] https://github.com/paritytech/polkadot-sdk/issues/5053
- [ ] https://github.com/paritytech/polkadot-sdk/issues/4

#### Enhancements (Nice to have)

- [ ] https://github.com/paritytech/polkadot-sdk/issues/5406
    - _Partially supported our polkadot-sdk fork_
- [x] https://github.com/paritytech/polkadot-sdk/issues/5312
    - _Patched our polkadot-sdk fork_
- [x] https://github.com/paritytech/polkadot-sdk/issues/5397
    - Implemented using a custom request-response protocol
